---
before:
  hooks:
    - make deps
builds:
  - main: ./cmd/rfoutlet/main.go
    binary: rfoutlet
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 7
    hooks:
      pre: packr
      post: packr clean
  - main: ./cmd/rfsniff/main.go
    binary: rfsniff
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 7
  - main: ./cmd/rftransmit/main.go
    binary: rftransmit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
    goarm:
      - 7
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
