language: go
sudo: false
env:
  - GO111MODULE=on
matrix:
  include:
    - go: 1.11.x
    - go: 1.x
      env: LATEST=true
    - go: tip
      env: TAGS=integration
  allow_failures:
    - go: tip
install:
  - make deps
script:
  - make vet
  - if [ -z $TAGS ]; then make coverage; else make test; done
after_success:
  - bash <(curl -s https://codecov.io/bash)
