language: go
sudo: false
go: 1.11.x
env:
  - GO111MODULE=on
install:
  - make deps
script:
  - make vet
  - make coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
