---
version: '3'
services:
  rfoutlet:
    container_name: rfoutlet
    image: mohmann/rfoutlet:latest
    # Uncomment if you want to build the image yourself:
    #
    # build: .
    ports:
      - '3333:3333'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH:-./configs/config.yml}:/etc/rfoutlet/config.yml:ro
      # set "state_file: state.json" in config.yml to store
      # the outlet state in the state-storage volume to
      # persist it across container restarts.
      - state-storage:/state-storage
    working_dir: /state-storage
    privileged: true
    restart: unless-stopped
volumes:
  state-storage: {}
